# Esse docker-compose é usado para rodar um container MySQL como seu banco de dados.
# Para usá-lo, execute no terminal: docker-compose up -d --build

version: '3'
services:
  dbmysql:
    image: mysql:8.0.21
    container_name: hotel_manager_db_mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    env_file:
      - .env
    restart: 'always'


#version: '3'
#services:
#  db:
#    image: mcr.microsoft.com/azure-sql-edge:latest
#    container_name: hotel_booking_manager_db
#    ports:
#        - 1433:1433
#    environment:
#      - ACCEPT_EULA=Y
#      - MSSQL_SA_PASSWORD=HotelManager!
#      - MSSQL_PID=Developer
